package InterfazGrafica;

import DAOs.*;
import Modelos.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class RegistrarSucursalAdmin extends javax.swing.JFrame {

    private Usuario activo;
    private UsuarioDAO usuarioDao = new UsuarioDAO();
    private SucursalDAO sucursalDao = new SucursalDAO();

    private ArrayList<Usuario> usuarios = new ArrayList<>();
    private ArrayList<Sucursal> sucursales = new ArrayList<>();

    public RegistrarSucursalAdmin(Usuario activo) {
        initComponents();
        this.activo = activo;
        enlistarUsuariosSucursales();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListSucursales = new javax.swing.JList<>();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListUsuarios = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreSucursal = new javax.swing.JTextField();
        btnSucursal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombreAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(JListSucursales);

        btnRegresar.setText("Regresar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sucursales y usuarios existentes:");

        jLabel2.setText("Sucursales:");

        jLabel3.setText("Usuarios:");

        jScrollPane2.setViewportView(JListUsuarios);

        jLabel4.setText("Nueva Sucursal:");

        jLabel5.setText("Nombre:");

        btnSucursal.setText("Registrar sucursal");
        btnSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalActionPerformed(evt);
            }
        });

        jLabel6.setText("Nuevo Administrador:");

        jLabel7.setText("Nombre:");

        btnAdmin.setText("Registrar admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdmin)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(txtNombreSucursal)
                        .addComponent(btnSucursal)
                        .addComponent(txtNombreAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSucursal)))
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalActionPerformed
        crearSucursal();
    }//GEN-LAST:event_btnSucursalActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        crearAdmin();
    }//GEN-LAST:event_btnAdminActionPerformed

    
    private void crearAdmin(){
    
        if (txtNombreAdmin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Ingrese el nombre del nuevo admin ", "ADVERTENSIA", 
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            String nombre = txtNombreAdmin.getText().trim();
            if (usuarioDao.crearAdmin(nombre)) {
                //si sale todo bien
                JOptionPane.showMessageDialog(null,"Administrador de tienda creado con exito ", "Todo bien", 
                    JOptionPane.PLAIN_MESSAGE);
            }else{
            JOptionPane.showMessageDialog(null,"Este usuario ya existe ", "ERROR", 
                    JOptionPane.ERROR_MESSAGE);
            }
        
        }
        
        enlistarUsuariosSucursales();
    }
    
    
    private void crearSucursal(){
    
        if (txtNombreSucursal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Ingrese el nombre de la nueva sucursal ", "ADVERTENSIA", 
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            String nombre = txtNombreSucursal.getText().trim();
            if (sucursalDao.crearSucursal(nombre)) {
                //si sale todo bien
                JOptionPane.showMessageDialog(null,"Sucursal creada con exito ", "Todo bien", 
                    JOptionPane.PLAIN_MESSAGE);
            }else{
            JOptionPane.showMessageDialog(null,"Esta sucursal ya existe ", "ERROR", 
                    JOptionPane.ERROR_MESSAGE);
            }
        
        }
        
        enlistarUsuariosSucursales();
    }
    
    private void enlistarUsuariosSucursales() {

        usuarios = usuarioDao.obtenerUsuarios();//obtiene los usuarios de la DB
        sucursales = sucursalDao.obtenerSucursales();//obtiene las sucursales de la DB

        DefaultListModel<String> modelo1 = new DefaultListModel<>();

        for (Usuario user : usuarios) {
            modelo1.addElement(user.getNombre());
        }

        DefaultListModel<String> modelo2 = new DefaultListModel<>();

        for (Sucursal sucursal : sucursales) {
            modelo2.addElement(sucursal.getNombre_sucursal());
        }

        JListUsuarios.setModel(modelo1);//se enlistan los nombres de los usuarios
        JListSucursales.setModel(modelo2);//se enlistan los nombres de las sucursales

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListSucursales;
    private javax.swing.JList<String> JListUsuarios;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNombreAdmin;
    private javax.swing.JTextField txtNombreSucursal;
    // End of variables declaration//GEN-END:variables
}
